### ISSUE TITLE
Extract function called createMessage

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-release-bot#6]
## Background

This project is used to ping Core Teams when an Ember release date is approaching.

## Problem

In `cron/daily-message.js`, the `job` function does 1 thing (it sends a message to each `channel`) but has around 50 lines of code. For a new contributor, the code may not be immediately clear.

Let's practice 2 refactoring techniques, "extract function" and "make early exits," to clean up `job`.

## TODOs

Notice, in [lines 29-53](https://github.com/ember-learn/ember-release-bot/blob/8b0b313b5a1fcb758771c8f1df738a6d705916d2/cron/daily-message.js#L29-L53), how there are multiple calls of `channel.send()`. The only difference is what `message` we send. This motivates us to think about a function that can return the correct `message`. We'll call this function `createMessage`.

When refactoring code, I recommend taking small steps. **First, open a pull request (PR) after creating your PR branch. After completing each step below, please make a commit and push to GitHub, even if the tests may fail.** Taking initial steps may feel daunting (a common symptom when a tech debt is present), but the final steps will feel like a breeze.

- [ ] In line 4 (before `module.exports`), create the function `createMessage`. Don't worry about its inputs.

    <details>
    <summary>Hint</summary>

    ```javascript
    const moment = require('moment');
    const _ = require('lodash');

    function createMessage() {
    }

    module.exports = { ... }
    ```

    </details>

- [ ] Copy-paste the [nested if statement](https://github.com/ember-learn/ember-release-bot/blob/8b0b313b5a1fcb758771c8f1df738a6d705916d2/cron/daily-message.js#L29-L53) into `createMessage`.

    <details>
    <summary>Hint</summary>

    ```javascript
    function createMessage() {
      // more than 5 days means that it's not release week
      if (dayDiff === -11) {
        channel.send(`Release week starts next week on ${moment(dateString).format('YYYY-MM-DD')} are we all prepared? :lts:`);
      } else if (dayDiff === -4) {
      ...
    }
    ```

    </details>

- [ ] In `createMessage`, replace every `channel.send()` with a `return` statement.

    <details>
    <summary>Hint</summary>

    ```javascript
    function createMessage() {
      // more than 5 days means that it's not release week
      if (dayDiff === -11) {
        return `Release week starts next week on ${moment(dateString).format('YYYY-MM-DD')} are we all prepared? :lts:`;
      } else if (dayDiff === -4) {
      ...
    }
    ```

    </details>

- [ ] In `createMessage`, we have already made early exits. We can now remove `else` statements.

    <details>
    <summary>Hint</summary>

    ```javascript
    function createMessage() {
      // more than 5 days means that it's not release week
      if (dayDiff === -11) {
        return `Release week starts next week on ${moment(dateString).format('YYYY-MM-DD')} are we all prepared? :lts:`;
      }

      if (dayDiff === -4) {
      ...
    }
    ```

    </details>

- [ ] Study the code in `createMessage`. Enumerate the variables that aren't defined in the function, and make these the inputs to the function.

    <details>
    <summary>Hint</summary>

    ```javascript
    function createMessage({ dateString, dayDiff, waitingFor }) {
      if (!dateString) {
        return;
      }

      // more than 5 days means that it's not release week
      if (dayDiff === -11) {
        return `Release week starts next week on ${moment(dateString).format('YYYY-MM-DD')} are we all prepared? :lts:`;
      }

      if (dayDiff === -4) {
      ...
    }
    ```

    </details>

- [ ] We can start to simplify the `job` method. Replace the [nested if statement](https://github.com/ember-learn/ember-release-bot/blob/8b0b313b5a1fcb758771c8f1df738a6d705916d2/cron/daily-message.js#L29-L53) with a single `channel.send()`.

    <details>
    <summary>Hint</summary>

    ```javascript
    job(client, keyv) {
      return async () => {
        ...

        waitingFor = _.compact(waitingFor);

        const message = createMessage({ dateString, dayDiff, waitingFor });

        if (!message) {
          return;
        }

        channels.forEach((channel) => {
          channel.send(message);
        });
      }
    }
    ```

    </details>

- [ ] Lastly, notice that [`dayDiff` can be constructed from `dateString`](https://github.com/ember-learn/ember-release-bot/blob/8b0b313b5a1fcb758771c8f1df738a6d705916d2/cron/daily-message.js#L10-L14). In addition, `dayDiff` is not used inside `job` function for anything other than a call to `createMessage`. How can we remove 1 input dependency from `createMessage`?

    <details>
    <summary>Hint</summary>

    ```javascript
    function createMessage({ dateString, waitingFor }) {
      if (!dateString) {
        return;
      }

      const date = moment(dateString).add(5, 'days');
      const dayDiff = moment().diff(date, 'days');

      // more than 5 days means that it's not release week
      if (dayDiff === -11) {
        return `Release week starts next week on ${moment(dateString).format('YYYY-MM-DD')} are we all prepared? :lts:`;
      }

      if (dayDiff === -4) {
      ...
    }
    ```

    </details>

## References

- [3 Refactoring Techniques](https://crunchingnumbers.live/2020/08/08/3-refactoring-techniques/)

**Comment by ijlee2** [comment]
General notes: Hi, everyone. To allow more people to participate in Hacktoberfest, please claim only 1 issue labelled with `Hacktoberfest` in this repo (unless there are no others who can help). 🙂

Please check `#hacktoberfest` on [Discord](https://discord.gg/emberjs) to find other repos that can use your help. Thanks and happy Hacktoberfest!

**Comment by dhruvx24** [comment]
Hey @ijlee2  Can i take this issue ?

**Comment by ijlee2** [comment]
@parikhdhruv24791 Yep, thanks! Let us know if you have any questions.
